### ISSUE TITLE
Buildpack not working

### ISSUE THREAD

**Issue by PyroSteveJr** [mchung/heroku-buildpack-wordpress#20]
Following guide from http://mchung.github.io/heroku-buildpack-wordpress/ & everytime I get to the "heroku config:add BUILDPACK_URL=https://github.com/mchung/heroku-buildpack-wordpress.git" section it says it's setting config vars but fails and says resource not found.

Any ideas?

**Comment by nevinlaughlin** [comment]
I'm getting a similar problem. I followed the guide and used the above mention config:set command, but still getting my push rejected. Any ideas?


$ heroku config:set BUILDPACK_URL=https://github.com/mchung/heroku-buildpack-wordpress.git
Your version of git is 1.9.3. Which has serious security vulnerabilities.
More information here: https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x
Setting config vars and restarting afternoon-beyond-3063... done, v4
BUILDPACK_URL: https://github.com/mchung/heroku-buildpack-wordpress.git
$ git push heroku master
Counting objects: 569, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (442/442), done.
Writing objects: 100% (569/569), 1.64 MiB | 1.91 MiB/s, done.
Total 569 (delta 111), reused 566 (delta 111)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> WordPress app detected
remote: -----> Installing Nginx v1.4.2
remote: -----> Installing PHP v5.5.2
remote: -----> Installing WordPress v3.9.1
remote:        WORDPRESS_DIR not set. Installing WordPress to /
remote: -----> Writing start.sh script
remote: -----> Done with compile
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for WordPress -> web
remote: 
remote: -----> Compressing... done, 35.9MB
remote: -----> Launching... 
remote:  !     Push rejected, failure creating release
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to afternoon-beyond-3063.
remote: 
To https://git.heroku.com/afternoon-beyond-3063.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/afternoon-beyond-3063.git'

Thanks!
